/* C-HUB English Academy — bundled offline curriculum and local progress */
(()=>{'use strict';
const root=document.getElementById('english-academy');if(!root)return;
const STORE='chub_english_academy_v1';
const levels=[
{title:'English Starter',emoji:'🌱',desc:'Build your first English words and sentences.',lessons:[
['Greetings & introductions','Use friendly greetings. “Hello! My name is Rina.” “How are you?” — “I am fine, thank you.”','Choose the best reply to “How are you?”',['I am fine, thank you.','My name ten.','Good night morning.'],0,'“I am fine, thank you” answers a question about how someone feels.','“How are you?” ର ଉତ୍ତର “I am fine, thank you.” ହୋଇପାରେ।'],
['Everyday objects','A book, a pen, a bag, a desk. Use “This is a…” for one object.','Complete: This is ___ apple.',['a','an','are'],1,'Use “an” before a vowel sound. Apple begins with a vowel sound.','Apple ସ୍ୱରଧ୍ୱନିରୁ ଆରମ୍ଭ ହୁଏ, ତେଣୁ “an apple”।'],
['Numbers & days','Numbers: one, two, three. Days: Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday.','Which day comes after Monday?',['Sunday','Tuesday','Friday'],1,'Tuesday comes after Monday.','Monday ପରେ Tuesday ଆସେ।']]},
{title:'Sentence Builder',emoji:'🧱',desc:'Turn words into clear sentences.',lessons:[
['Subject + verb + object','A simple sentence can follow Subject + Verb + Object: “Mina reads a book.” Mina = subject; reads = verb; a book = object.','Choose the correct sentence.',['Reads Mina book a.','Mina reads a book.','A book Mina reads?'],1,'English statements usually place the subject before the verb.','ସାଧାରଣ ବାକ୍ୟରେ subject ପ୍ରଥମେ, ପରେ verb ଆସେ।'],
['I am / You are / He is','I am ready. You are kind. He is a student. She is happy. It is small. We/They are ready.','Choose the correct sentence.',['She are happy.','I is ready.','They are ready.'],2,'Use “are” with they.','They ସହିତ “are” ବ୍ୟବହାର କରାଯାଏ।'],
['Make a question','Move am/is/are before the subject: “You are ready.” → “Are you ready?” Add a question mark.','Make a question: “He is at home.”',['Is he at home?','He is at home?','At home he?'],0,'Put “is” before “he” to make the question.','ପ୍ରଶ୍ନ କରିବାକୁ “is” କୁ “he” ପୂର୍ବରୁ ରଖନ୍ତୁ।']]},
{title:'Grammar Explorer',emoji:'🧭',desc:'Understand the patterns behind good English.',lessons:[
['Nouns & pronouns','A noun names a person, place, thing or idea: teacher, Odisha, book, honesty. Pronouns replace nouns: he, she, it, they.','Which word is a pronoun?',['teacher','they','school'],1,'“They” can replace the names of people or things.','“They” ଏକ pronoun; ଏହା ନାମ ବଦଳରେ ବ୍ୟବହାର ହୁଏ।'],
['Articles: a, an, the','Use a/an for a non-specific singular countable noun; choose by sound. Use “the” for something specific: “the sun”.','Choose the correct phrase.',['a orange','an orange','an book'],1,'“Orange” begins with a vowel sound, so use “an”.','Orange ର ଆରମ୍ଭ ସ୍ୱରଧ୍ୱନି, ତେଣୁ “an orange”।'],
['Present & past','Present: “She plays.” Past: “She played yesterday.” For “be”: am/is/are → was/were.','Yesterday, we ___ at school.',['are','were','is'],1,'“Yesterday” points to the past; “we” pairs with “were”.','Yesterday ଅତୀତକୁ ବୁଝାଏ; “we were” ଠିକ୍।']]},
{title:'Spoken English',emoji:'🗣️',desc:'Speak politely in class and everyday life.',lessons:[
['Classroom English','Useful phrases: “May I come in?” “Could you please repeat that?” “I don’t understand yet.”','You did not hear the teacher. What can you say?',['Speak louder now!','Could you please repeat that?','I am not listen.'],1,'This is a polite and clear request.','ଏହା ଭଦ୍ର ଭାବରେ ପୁଣି କହିବାକୁ ଅନୁରୋଧ।'],
['Polite requests','Use “please” to make requests polite: “Could you help me, please?” Reply: “Of course” or “Certainly.”','Choose a polite request.',['Give me your pen.','Could I borrow your pen, please?','Pen now.'],1,'“Could I… please?” sounds respectful.','“Could I… please?” ଭଦ୍ର ଅନୁରୋଧ।'],
['Self-introduction','A simple introduction: “Good morning. My name is Anil. I am a student. I live in Odisha. I enjoy reading.”','Which sentence tells your name?',['I am twelve years old.','My name is Anil.','I enjoy reading.'],1,'“My name is…” is used to tell your name.','ନିଜ ନାମ କହିବାକୁ “My name is…” ବ୍ୟବହାର କରନ୍ତୁ।']]},
{title:'Writing Academy',emoji:'✍️',desc:'Write accurate sentences and short paragraphs.',lessons:[
['Build a correct sentence','Start with a capital letter and end with punctuation. Example: “My school is near my home.”','Which sentence is punctuated correctly?',['my school is nice','My school is nice.','My School is nice'],1,'A sentence starts with a capital letter and ends with a full stop here.','ବାକ୍ୟର ଆରମ୍ଭରେ capital letter ଓ ଶେଷରେ full stop ଦିଅନ୍ତୁ।'],
['Paragraph structure','A paragraph focuses on one topic. Begin with a topic sentence, add supporting details, then finish with a closing sentence.','What should a paragraph mainly have?',['Many unrelated topics','One clear main idea','Only a title'],1,'A focused paragraph develops one main idea.','ଗୋଟିଏ ଅନୁଛେଦରେ ମୁଖ୍ୟତଃ ଗୋଟିଏ ଭାବ ରହିବା ଉଚିତ।'],
['Formal email basics','Use a clear subject, polite greeting, short purpose, relevant details, and a courteous closing. Never invent facts in a formal message.','Which greeting is suitable for a formal email to a teacher?',['Hey dude,','Respected Sir/Madam,','Yo!'],1,'A respectful greeting suits a formal email.','ଶିକ୍ଷକଙ୍କୁ ଔପଚାରିକ ଇମେଲ୍‌ରେ ସମ୍ମାନଜନକ ସମ୍ବୋଧନ ଉପଯୁକ୍ତ।']]},
{title:'Advanced English',emoji:'🚀',desc:'Express complex ideas with clarity and precision.',lessons:[
['Connectors & transitions','Connect ideas with however (contrast), therefore (result), moreover (addition), and although (concession).','Choose a connector: It was raining; ___, the match continued.',['therefore','however','because of'],1,'“However” shows contrast between rain and the match continuing.','“However” ବିପରୀତ ଭାବକୁ ଯୋଡ଼େ।'],
['Formal vocabulary','Prefer precise words in formal writing: “assist” instead of “help” when suitable; “purchase” instead of “buy”; avoid slang.','Which is most formal?',['Gonna do it','I will complete the task.','Do it ASAP bro'],1,'This sentence is clear and appropriately formal.','ଏହି ବାକ୍ୟ ସ୍ପଷ୍ଟ ଓ ଔପଚାରିକ।'],
['Edit & proofread','Proofread for subject–verb agreement, tense consistency, spelling, capital letters and punctuation. Example: “She goes”, not “She go”.','Correct the sentence: “He go to school every day.”',['He goes to school every day.','He going school every day.','He gone to school every day.'],0,'With he/she/it in the simple present, most verbs take -s/-es.','Simple present ରେ he/she/it ସହିତ ସାଧାରଣତଃ verb ରେ -s/-es ଯୋଡ଼ାଯାଏ।']]}
];
const allLessons=levels.flatMap((l,li)=>l.lessons.map((x,si)=>({id:`${li}-${si}`,level:li,index:si,title:x[0],teach:x[1],q:x[2],opts:x[3],correct:x[4],why:x[5],or:x[6]})));
const blank=()=>({xp:0,completed:[],answers:{},streak:0,lastDay:'',goal:3,settings:{sound:false},badges:[]});let state;try{state=Object.assign(blank(),JSON.parse(localStorage.getItem(STORE)||'{}'));}catch(_){state=blank()}if(!Array.isArray(state.completed))state.completed=[];if(!state.answers)state.answers={};if(!state.settings)state.settings={sound:false};
const save=()=>{try{localStorage.setItem(STORE,JSON.stringify(state));}catch(_){status('Storage is full or unavailable. Progress may not save.')}};
const $=id=>root.querySelector('#'+id);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let selected=0,current=null,answered=false;
function day(){return new Date().toLocaleDateString('en-CA')}function updateStreak(){let d=day();if(state.lastDay!==d){let prev=new Date();prev.setDate(prev.getDate()-1);let pd=prev.toLocaleDateString('en-CA');state.streak=state.lastDay===pd?(state.streak||0)+1:1;state.lastDay=d;save()}}
function status(msg){let n=$('ea-status');if(n)n.textContent=msg}function playWin(){if(!state.settings.sound)return;try{let C=window.AudioContext||window.webkitAudioContext;if(!C)return;let c=new C(),o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=660;g.gain.value=.045;o.connect(g);g.connect(c.destination);o.start();o.frequency.setValueAtTime(880,c.currentTime+.09);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.22);o.stop(c.currentTime+.23);o.onended=()=>c.close()}catch(_){}}function unlocked(l,s){if(l===0&&s===0)return true;let prev=l+'-'+(s-1);if(s>0)return state.completed.includes(prev);let last=levels[l-1].lessons.length-1;return state.completed.includes((l-1)+'-'+last)}
function render(){let done=state.completed.length,percent=Math.round(done/allLessons.length*100),rank=state.xp>=1200?'English Master':state.xp>=650?'Word Wizard':state.xp>=300?'Sentence Star':state.xp>=100?'Grammar Scout':'Word Explorer';$('ea-xp').textContent=state.xp;$('ea-rank').textContent=rank;$('ea-streak').textContent=state.streak||0;$('ea-done').textContent=done+'/'+allLessons.length;$('ea-bar').style.width=percent+'%';$('ea-percent').textContent=percent+'% complete';$('ea-online').textContent=navigator.onLine?'🟢 Ready • local lessons available offline':'📴 Offline • local lessons ready';$('ea-level-label').textContent=levels[selected].title;$('ea-levels').innerHTML=levels.map((l,i)=>`<button class="ea-level ${i===selected?'active':''}" data-level="${i}" type="button"><span class="emoji">${l.emoji}</span><strong>${i+1}. ${l.title}</strong><small>${l.desc}</small><div class="ea-progress"><i style="width:${Math.round(l.lessons.filter((_,s)=>state.completed.includes(i+'-'+s)).length/l.lessons.length*100)}%"></i></div><small>${l.lessons.filter((_,s)=>state.completed.includes(i+'-'+s)).length}/${l.lessons.length} lessons</small></button>`).join('');$('ea-lessons').innerHTML=levels[selected].lessons.map((l,s)=>{let id=selected+'-'+s,done=state.completed.includes(id),open=unlocked(selected,s);return `<button class="ea-lesson" type="button" data-lesson="${id}" ${open?'':'disabled'}><span class="num">${done?'✓':open?'▶':'🔒'}</span><span><b>${esc(l[0])}</b><small>${done?'Completed • practice again':open?'Tap to learn':'Complete the previous lesson to unlock'}</small></span></button>`}).join('');let badges=[];if(done>=1)badges.push('🌟 First Lesson');if(done>=3)badges.push('🔥 3 Lessons');if(state.xp>=100)badges.push('📘 100 XP');if(state.streak>=3)badges.push('🔥 3-Day Streak');if(done===allLessons.length)badges.push('🏆 Academy Graduate');$('ea-badges').innerHTML=badges.length?badges.map(b=>`<span class="ea-badge">${b}</span>`).join(''):'<span class="ea-muted">Complete lessons to earn your first badge.</span>';}
function openLesson(id){current=allLessons.find(x=>x.id===id);if(!current)return;answered=false;$('ea-practice').hidden=false;$('ea-lesson-title').textContent=current.title;$('ea-teach').textContent=current.teach;$('ea-question').textContent=current.q;$('ea-feedback').hidden=true;$('ea-next').hidden=true;$('ea-writing-area').hidden=true;$('ea-options').innerHTML=current.opts.map((o,i)=>`<button type="button" class="ea-option" data-answer="${i}">${esc(o)}</button>`).join('');$('ea-practice').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});}
function answer(i){if(answered)return;answered=true;let ok=i===current.correct;let buttons=$('ea-options').querySelectorAll('button');buttons.forEach((b,j)=>{if(j===current.correct)b.classList.add('correct');else if(j===i)b.classList.add('wrong');b.disabled=true});let first=!state.completed.includes(current.id);if(ok&&first){state.xp+=10;state.completed.push(current.id);state.answers[current.id]=true;updateStreak();playWin();}else if(!ok){state.answers[current.id]=false;}save();$('ea-feedback').hidden=false;$('ea-feedback').className='ea-feedback '+(ok?'good':'bad');$('ea-feedback').innerHTML=`<b>${ok?'✅ Correct! +'+(first?10:0)+' XP':'💡 Not quite — try again next time.'}</b><p>${esc(current.why)}</p><p lang="or">${esc(current.or)}</p>${!ok?'<p>Practice is unlimited. Read the explanation and retry this lesson.</p>':''}`;$('ea-next').hidden=false;$('ea-next').textContent=ok?'Continue':'Retry lesson';if(ok){$('ea-practice').classList.remove('ea-toast');void $('ea-practice').offsetWidth;$('ea-practice').classList.add('ea-toast')}render();}
root.addEventListener('click',e=>{let lv=e.target.closest('[data-level]');if(lv){selected=Number(lv.dataset.level);render();return}let lesson=e.target.closest('[data-lesson]');if(lesson){openLesson(lesson.dataset.lesson);return}let opt=e.target.closest('[data-answer]');if(opt){answer(Number(opt.dataset.answer));return}});
$('ea-next').addEventListener('click',()=>{if(!current)return;if(!answered){openLesson(current.id);return}if(state.completed.includes(current.id)){let idx=allLessons.findIndex(x=>x.id===current.id),next=allLessons.slice(idx+1).find(x=>unlocked(x.level,x.index));if(next){selected=next.level;render();openLesson(next.id);return}}openLesson(current.id)});
$('ea-continue').addEventListener('click',()=>{let next=allLessons.find(x=>!state.completed.includes(x.id)&&unlocked(x.level,x.index));if(!next)next=allLessons[0];selected=next.level;render();openLesson(next.id)});
$('ea-challenge').addEventListener('click',()=>{let d=Number(day().replace(/-/g,''));let x=allLessons[d%allLessons.length];selected=x.level;render();openLesson(x.id);status('Daily challenge: complete the selected lesson to practise today. XP is awarded only once per lesson.')});
$('ea-goal').addEventListener('change',e=>{state.goal=Math.max(1,Math.min(10,Number(e.target.value)||3));save();status('Daily goal saved on this device.')});$('ea-sound').addEventListener('click',()=>{state.settings.sound=!state.settings.sound;save();$('ea-sound').textContent='🔊 Sound: '+(state.settings.sound?'On':'Off');status('Sound preference saved. A short local celebration tone plays after a newly completed lesson when sound is on.')});window.addEventListener('online',render);window.addEventListener('offline',render);
$('ea-writing-check').addEventListener('click',()=>{let val=$('ea-writing').value.trim();$('ea-writing-result').hidden=false;$('ea-writing-result').textContent=val.length<15?'Try writing 1–3 complete sentences. Start with a capital letter and check punctuation.':'Good start! Compare your writing with this model: “My name is Rina. I am a student. I enjoy learning English.” Open-ended writing can have many correct answers; check meaning, grammar and punctuation.'});
$('ea-goal').value=state.goal||3;$('ea-sound').textContent='🔊 Sound: '+(state.settings.sound?'On':'Off');render();
})();
